### ISSUE TITLE
Analyzer get message from characteristic

### ISSUE THREAD

**Issue by isaacurbina** [davidgyoung/AdvetiserAnalyzer#1]
In Application.kt after this line

// We have found an apple background advertisement

What exactly is the code doing? How to request a characteristic from it?

**Comment by davidgyoung** [comment]
All this code is designed to be used with an iOS app that sequentially advertises a sequence of GATT Service UUIDs in the background, changing them at a specific time interval.  The code that follows the line you mention knows how the iOS app works and is essentially an automated reverse-engineering tool.  The end result is to find out an advertised service UUID sent by the IOS side that matches every bit position in the 128-bit overflow area bitmap.

This code is *NOT* designed to be used for any other purpose.

**Comment by isaacurbina** [comment]
From your blog http://www.davidgyoungtech.com/2020/05/07/hacking-the-overflow-area
`The next 16 bytes are a 128 bit bitmask. Each service UUID you advertise will cause exactly one of those 128 bits to be set to 1. In the example shown above, the very last bit in the bitmask is set to 1.`
These 16 bits are UUID or any random data right?

I get something like 00000101 00010000 00011100 00011010 11000100 11111101 00000001 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 11001011
but i'm unable to fetch major and minor which i know are 28 and 1 respectively, I can get some UUID but it doesn't match my own.
