### ISSUE TITLE
Decoding can't find more than 3 bits from 128

### ISSUE THREAD

**Issue by ZhestovskyYS** [davidgyoung/AdvetiserAnalyzer#2]
Hi, I want to exchange data from iOS to Android in background. So, I used this app to try how does that work. I intalled this app on my android device and installed this [companion app](https://github.com/davidgyoung/BackgroundAdvertiser) on iPhone. But "servicesForBitPosition" hashMap collects only 3 services while "services" variable  continue to collect UUID formatted bytes

**Comment by davidgyoung** [comment]
I have not run this app in a couple of years, so I am struggling a bit to remember details.

One thing to know is that the companion iOS app must be visible in the foreground for the bit to continue to change, as newer iOS versions prevent changing advertisements from the background.  So you must keep the iOS app on the screen at all times during the test.

**Comment by ZhestovskyYS** [comment]
I tried on iOS 13.3.1 and also removed rssi check to increase amount of checked records. And I have just tried to keep screen always on during the test but I got still the same results

**Comment by davidgyoung** [comment]
Can you tell if the Android app continues to get adverts from iOS but with the hit pattern not changing?   Or do the adverts from iOS stop being detected?

the reason I had the rssi filter was to prevent other iPhones from triggering the Android app — neighbors’ iPhones, people walking by, etc.  are you sure the iPhone being detected by Android is the one under test?  Perhaps you are picking up a different iPhone.

**Comment by ZhestovskyYS** [comment]
Looks like Android keep showing the same result even if the iOS app on my device is not running. My office is on the top floor of the building, so I thought that must be not so many corruption in signal by other devices

**Comment by davidgyoung** [comment]
Do you ever see the bits advertised by iOS change?  What if you uninstall and reinstall the iOS app?

**Comment by ZhestovskyYS** [comment]
No, Android see only two different signals

**Comment by ZhestovskyYS** [comment]
I came to conclutson, that Android device does not see overflow area signal
